services:
- type: web
  name: practice-planner-frontend
  env: node
  buildCommand: cd client && yarn install && yarn build
  startCommand: cd client && serve -s build
  envVars:
  - key: REACT_APP_API_URL
    fromService:
      name: database
      type: web
      property: url

- type: web
  name: practice-planner-backend
  env: node
  buildCommand: cd server && yarn install
  startCommand: cd server && yarn start:prod
  envVars:
  - key: MONGO_URI
    fromDatabase:
      name: Database-For-Practice-Planner
      property: connectionString
